### ISSUE TITLE
Resizing of messages pane isn't quite right

### ISSUE THREAD

**Issue by nzakas** [eslint/playground#28]
The messages pane under the editor should be resizable by dragging on the border between the editor and the pane.

Right now, you need to drag the lower-right corner of the pane to resize it. This probably means we can't rely on CSS resizing for this feature.

![Screenshot 2022-04-21 at 13-44-36 ESLint Playground](https://user-images.githubusercontent.com/38546/164549316-47be50b8-9710-4365-81fd-fa9e87fe7889.png)

**Comment by amareshsm** [comment]
#59
