### ISSUE TITLE
Show error on invalid rule config

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/playground#43]
`Linter` doesn't validate configurations so there's no info on misconfigured rules, and they will be executed with unsupported config values.

This is wrong severity level:

![image](https://user-images.githubusercontent.com/44349756/169049398-abbe2590-f127-47db-8484-43d910e382d3.png)

This is wrong value for the string option for this rule:

![image](https://user-images.githubusercontent.com/44349756/169049606-1d1521c7-db34-4fbb-a1ae-c6e1cfb0c3b2.png)

Also, since the AJV validation is not run on rule configs, default values specified in the schema will not be set. For example, if you configure `use-isnan` with `["error", { "enforceForIndexOf": true }]`, the rule will work as if `enforceForSwitchCase` was set to `false`, although the default value for this option is `true`.

**Comment by nzakas** [comment]
Sounds reasonable to me.

**Comment by snitin315** [comment]
I will add it 👍
