### ISSUE TITLE
Option to edit existing configuration.

### ISSUE THREAD

**Issue by amareshsm** [eslint/playground#44]
Like the download configuration option, Can give an option in UI to copy/paste and edit existing config JSON. It will be easier for the users if they have a config file.

**Comment by nzakas** [comment]
Interesting idea. One problem I see is that the playground doesn’t support plugins or custom parsers, so you wouldn’t actually be able to edit every config file. Given that most people are using plugins or custom parsers, I’m not sure this is worth the effort.

**Comment by nzakas** [comment]
I’m just not convinced that it’s a good idea to support only a subset of configs. I think it will be more confusing to people than helpful. But we can see if anyone else on the team feels differently.

**Comment by snitin315** [comment]
Yeah, providing half support would not be helpful to users.
