### ISSUE TITLE
Design considerations for mobile & Tablet device users

### ISSUE THREAD

**Issue by amareshsm** [eslint/playground#46]
Are we going to consider mobile/tablet device users for the playground site? The current site doesn't seem to be responsive and is not accessible on mobile/tablet. 

<img width="480" alt="image" src="https://user-images.githubusercontent.com/30730124/169281353-3593c05a-af13-424c-843d-fd674017e065.png">

I would like to know are going to consider mobile/tablet devices if yes I would like to work on this.

**Comment by nzakas** [comment]
Yes, the playground should still work on mobile and tablets (it was designed to), and we should be able to scroll. Happy to have the help!
