### ISSUE TITLE
Don't update URL on each keystroke

### ISSUE THREAD

**Issue by snitin315** [eslint/playground#69]
## Description

In the current playground implementation, we store configuration and options in URL (for link sharing purposes) on each keystroke. But, this actually pollutes the browser history:

<img width="644" alt="Screenshot 2022-05-06 at 3 49 47 PM" src="https://user-images.githubusercontent.com/46647141/172044869-dc84c52c-b074-46bb-b88c-9ed6ccbb03d2.png">

## Proposed Solution

Save configuration and update URL only when the user press `Ctrl/Cmd + S` or clicks the `Share URL` button.

I'll work on this issue.

**Comment by nzakas** [comment]
The problem with only updating periodically is that you could end up with a URL that doesn’t actually match what’s on the screen.  How will you account for that?

**Comment by snitin315** [comment]
This history issue seems to be present at the [typescript-playground](https://www.typescriptlang.org/play) as well. But they actually don't change it on every keystroke but on the following events:

- When `Ctrl + S` is pressed.
- When when we go to the URL bar and click, it updates the URL then as well.


https://user-images.githubusercontent.com/46647141/172979164-a64fbae8-c8ff-4a77-9afb-afb69e37903e.mov

**Comment by nzakas** [comment]
Ah interesting. In that case, I wonder if we just never update the URL bar and only allow to copy from the share location? 

@eslint/eslint-tsc thoughts?

**Comment by btmills** [comment]
We could use [`history.replaceState()`](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) instead to avoid creating new history entries.

**Comment by snitin315** [comment]
> We could use [history.replaceState()](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) instead to avoid creating new history entries.

That should work, I'll give it a try.

**Comment by snitin315** [comment]
We can use `.replaceState()` but it doesn't update the URL in the browser's URL bar. So the only option then will be to copy using the shareURL button. 

If we also update the URL (by passing the 3rd parameter), it still seems to [create history in the browser.](https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API#the_replacestate_method)

<img width="780" alt="Screenshot 2022-06-18 at 5 49 06 PM" src="https://user-images.githubusercontent.com/46647141/174437331-c3d82ff2-be2f-4fb0-950c-2b8591caa764.png">

**Comment by btmills** [comment]
@snitin315 check out https://github.com/eslint/playground/pull/77 and see if that does the trick. I'm seeing the intended behavior, so I hope it's not just my machine. (FWIW, I used the same code for the Prettier playground several years ago in https://github.com/prettier/prettier/pull/710. We don't need the feature detection anymore because caniuse reports full support.)

**Comment by nzakas** [comment]
I’m seeing the intended behavior too

**Comment by nzakas** [comment]
I’ve tested on Firefox and iOS/safari
