### ISSUE TITLE
Bug: No configuration available on mobile

### ISSUE THREAD

**Issue by nzakas** [eslint/playground#74]
We used to have the configuration options available in a drop down in mobile, but now the options are missing completely.

![B7EE0755-C2BC-4262-8F3F-78263F71BA02](https://user-images.githubusercontent.com/38546/173711012-65388c48-8be5-4641-8851-b0dbd2569450.png)

**Comment by snitin315** [comment]
I will look into it.

**Comment by snitin315** [comment]
I can see it on chrome, android.

![Screenshot_20220615-083255_Chrome](https://user-images.githubusercontent.com/46647141/173727949-5e968ff6-922d-4211-b41e-b6e12f782dea.jpg)

**Comment by amareshsm** [comment]
https://github.com/eslint/playground/blob/76af617f517df7ad23a8928fd5a8c40cf19237e3/src/playground/App.js#L133

`hidden` attribute is not needed.  I think it is causing the issue.
