### ISSUE TITLE
feat: change rule severity to select from input

### ISSUE THREAD

**Issue by harish-sethuraman** [eslint/playground#75]
Since the rule has only 3 severity `off`, `warn` and `error` can we have it as a select instead of input? I feel like it is kinda ambiguous to have it as input such that the user has to type completely and doesn't know what are the available severities. Is it okay if we could change it as select?

Also for all the rules that I've tried it doesn't allow multiple severities to be selected. Can we also default it to just the value instead of having an `["` and `"]`?

<img width="413" alt="Screenshot 2022-06-19 at 10 32 09 AM" src="https://user-images.githubusercontent.com/32865581/174466708-84e1adbb-62f0-49ea-b0f9-557129d63296.png">

I'd like to send a PR if the suggested change is okay

**Comment by snitin315** [comment]
Its not only severity. You can pass options here as well.

**Comment by harish-sethuraman** [comment]
We can get the options from the rules JSON right? we can populate them as well? Like a multi select?

**Comment by snitin315** [comment]
I don't think so. Some options can take any value from user input.

**Comment by harish-sethuraman** [comment]
Then how about splitting the options separately as input and severity separately as dropdown? Severity is always present right?

**Comment by snitin315** [comment]
I'm not sure if we want that or it's worth the effort here. Sounds like a bad UX to me. Right now its same as the way you cinfigure a rule in your config file.

**Comment by harish-sethuraman** [comment]
<img width="403" alt="Screenshot 2022-06-19 at 9 18 34 PM" src="https://user-images.githubusercontent.com/32865581/174489445-883820a1-9264-440e-a4c6-7e101a53c86f.png">
TBH I've used ES Lint,  but I never understood what that input field meant. It was prefilled with an string `error` in an array. It doesn't even have a placeholder that says what has to be entered inside the input?  Only after you told me I knew we can enter options there? 
Anyways we are going to have severity for the rules so it would be better to split them or atleast have a placeholder called options for the input field.

**Comment by snitin315** [comment]
I am still unsure about splitting since [passing an array is standard](https://eslint.org/docs/user-guide/configuring/rules#using-configuration-files). But we can definitely add some description about configuring options near `choose a rule` or `add a rule`.

/cc @eslint/eslint-tsc thoughts?

**Comment by nzakas** [comment]
I don't think it makes sense to have a dropdown for the severity, as that would clutter up the UI and force us to have two fields to configure each rule instead of one.

I'm honestly not too concerned about people not understanding how to configure rules in the playground. There are a lot of examples in the docs using arrays, and I'd rather have the playground configuration for a rule look similar to what you see inside a config file. 

I'm not against adding placeholder text in case the input is left empty. I just don't want to clutter up the UI with too many additional elements.

**Comment by mdjermanovic** [comment]
I agree with @snitin315 and @nzakas, the current single text input fields are fine because this matches how rules are configured in config files.

If we want to somehow indicate that these fields can be used to configure options, we could evaluate that enhancement.

**Comment by nzakas** [comment]
Closing as we aren’t going to make a change here.
