### ISSUE TITLE
Feature request: Add `Fix` button

### ISSUE THREAD

**Issue by micnic** [eslint/playground#81]
Add a `Fix` button to run eslint with `--fix` option.

**Comment by harish-sethuraman** [comment]
<img width="1277" alt="Screenshot 2022-06-24 at 1 56 52 PM" src="https://user-images.githubusercontent.com/32865581/175495792-3c261813-8572-42be-bee2-a4627e9e2b36.png">
There already is a fix button that runs `--fix` on the playground
