### ISSUE TITLE
Migrate playground to eslint.org repository

### ISSUE THREAD

**Issue by btmills** [eslint/playground#93]
In the 2022-06-30 TSC meeting, @nzakas [suggested](https://github.com/eslint/tsc-meetings/issues/358#issuecomment-1167715271) migrating this into the [eslint/eslint.org](https://github.com/eslint/eslint.org/) repository:

> Agenda item: should we move the playground into the eslint.org repo? The original plan was for it to be on a separate domain, but since we changed that, I don’t know that it makes sense to have a separate repo. The current repo just has an Eleventy wrapper that embeds the React app. We could eliminate duplication of things like the header by moving it into the eslint.org repo. Plus, this would allow us to easily produce translated versions of the playground.

All were in favor.

**Comment by mdjermanovic** [comment]
PR https://github.com/eslint/eslint.org/pull/268
